name: Publish

on: 
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
    - name: Set up mpkg
      env:
        repo: ${{ github.repository }}
      run: |
        pip install git+https://github.com/mpkg-project/mpkg.git -q
        #pip install mpkg==0.0.6
        python3 main.py $repo
        echo "date=$(date +%y%m%d)" >> $GITHUB_ENV
    - name: Upload data to AutoBuild
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/*
        tag: AutoBuild
        overwrite: true
        file_glob: true
    - name: Upload scoop.json to AutoBuild
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: scoop.json
        tag: AutoBuild
        overwrite: true
        file_glob: true
    - name: Upload data to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/*
        tag: ${{ env.date }}
        overwrite: true
        file_glob: true
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "$(date +%y%m%d)" > ver.txt
        git add ver.txt
        if [ -n "$(git status -s)" ]; then git commit -m "ver: $(date +%y%m%d)"; fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
