name: Publish

on: 
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
    - name: Set up mpkg
      env:
        repo: ${{ github.repository }}
      run: |
        mkdir release
        pip install https://github.com/mpkg-project/mpkg/archive/master.zip -q
        python3 main.py $repo
        echo "date=$(date +%y%m%d)" >> $GITHUB_ENV
        ls -al release
    - name: Upload data to AutoBuild
      uses: softprops/action-gh-release@v1
      with:
        tag_name: AutoBuild
        files: |
          auto/*
          release/*
    - name: Upload data to new tag
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.date }}
        files: |
          release/*
